import { z } from 'zod';
import { CUSTOMER_ID, yearEndpoint } from './site.ts';

/**
 * Reading the year endpoint, and cutting its HTML into rows.
 *
 * The response is `[count, html]` — a JSON array whose second element is the rendered list the page
 * would have shown. There is no JSON-LD and no microdata anywhere on this site, so the markup is
 * the only structure there is. It is regular markup, generated by a CMS from a database, which is
 * what makes reading it defensible: the fields below are separate elements with their own classes,
 * not words picked out of a sentence.
 *
 * Hand-written patterns rather than a DOM library, like `app/src/lib/server/page-event.ts` and
 * `importers/bakhagen`: seven fields out of one card shape is not worth a parser dependency.
 */

/** `[9, "<div class=\"month-block\">…"]` — anything else is a redesign, not an empty year. */
const responseSchema = z.tuple([z.union([z.number(), z.string()]), z.string()]);

export type UpstreamCard = {
	/**
	 * The CMS's own activity id, off the end of the card's link.
	 *
	 * Empty for a card whose link is a `mailto:` sign-up rather than a page of its own — two of the
	 * twelve in the committed response are. `map.ts` derives a key for those; see `externalIdFor`.
	 */
	id: string;
	/** The link's query string, or empty where the card links somewhere else entirely. */
	query: string;
	title: string;
	/** The year, from the month heading this card sits under — the only place it is written. */
	year: number;
	/** The month name as the card spells it, in Norwegian. */
	month: string;
	day: string;
	/** `08:00 - 09:50`, or just a start. Taken verbatim; `map.ts` decides what it means. */
	time: string | null;
	venue: string | null;
	/** The card's background image, which is the only picture this source offers. */
	imageUrl: string | null;
};

export type Parsed = { rows: UpstreamCard[]; rejected: string[] };

function decode(value: string): string {
	return value
		.replace(/<[^>]*>/g, ' ')
		.replace(/&nbsp;/g, ' ')
		.replace(/&amp;/g, '&')
		.replace(/&quot;/g, '"')
		.replace(/&#0?39;|&apos;/g, "'")
		.replace(/&lt;/g, '<')
		.replace(/&gt;/g, '>')
		.replace(/\s+/g, ' ')
		.trim();
}

function pick(card: string, pattern: RegExp): string | null {
	const match = pattern.exec(card);
	const value = match?.[1] ? decode(match[1]) : null;
	return value || null;
}

/**
 * The year off a month heading.
 *
 * Spelled "Jan 2026" in this response and "Oktober" with no year on the page itself, which is the
 * whole reason this importer asks the endpoint rather than reading the page. A heading with no
 * four-digit year is therefore not something to work around — it means we are reading the wrong
 * thing, and every card under it is refused.
 */
function headingYear(heading: string): number | null {
	const match = /\b(20\d{2})\b/.exec(heading);
	return match?.[1] ? Number(match[1]) : null;
}

export function parseYear(body: unknown): Parsed {
	const outer = responseSchema.safeParse(body);
	if (!outer.success) {
		throw new Error(`unexpected year response: ${outer.error.issues[0]?.message}`);
	}

	const html = outer.data[1];
	const rows: UpstreamCard[] = [];
	const rejected: string[] = [];

	// One pass per month block, so each card is read with the year of the heading above it.
	const blocks = html.split(/(?=<div class="month-block">)/).filter((b) => b.includes('act-unit'));
	for (const block of blocks) {
		const heading = pick(block, /<div class="main-month[^"]*">([\s\S]*?)<\/div>/) ?? '';
		const year = headingYear(heading);

		for (const card of block.split(/(?=<div class="act-unit">)/).slice(1)) {
			/*
			 * The link, which is not always to an event page.
			 *
			 * Most cards link to `?<slug>-<id>` on the calendar itself. Two of the twelve in the
			 * committed response link to a `mailto:` instead — "sign up by writing to me" — and
			 * those are real activities with no page and no id. Taking the id only from a query
			 * string keeps `id` meaning "the CMS's own", and leaves the rest to `map.ts`.
			 */
			const link = /<a [^>]*href="([^"]+)"/.exec(card)?.[1] ?? '';
			const query = link.startsWith('?') ? link.slice(1) : '';
			const id = /-(\d+)$/.exec(query)?.[1] ?? '';
			const title = pick(card, /<h2>([\s\S]*?)<\/h2>/);

			if (!title) {
				rejected.push(`card with no title: ${decode(card).slice(0, 60)}`);
				continue;
			}
			if (!year) {
				rejected.push(`${title}: no year in the month heading "${heading}"`);
				continue;
			}

			rows.push({
				id,
				query,
				title,
				year,
				month: pick(card, /<section class="month">([\s\S]*?)<\/section>/) ?? '',
				day: pick(card, /<section class="big">([\s\S]*?)<\/section>/) ?? '',
				time: pick(card, /<time>([\s\S]*?)<\/time>/),
				// Their own class name is misspelled. Matched as it is written, not as it should be.
				venue: pick(card, /<div class="loacation-text">([\s\S]*?)<\/div>/),
				imageUrl: /background-image:\s*url\('([^']+)'\)/.exec(card)?.[1]?.trim() ?? null
			});
		}
	}

	return { rows, rejected };
}

const HEADERS = {
	// Identifying, with a contact URL, as docs/event-sources.md asks of every importer.
	'user-agent': 'hendingar.no importer (+https://hendingar.no)',
	'content-type': 'application/x-www-form-urlencoded',
	accept: 'application/json, text/javascript, */*'
};

export type Read = (year: number) => Promise<unknown>;

/**
 * One request per year, with the parameters the page's own filter sends.
 *
 * `t` is the year, and the three empty fields are the other filters left unset — category, path
 * and language. Sent exactly as the site sends them, because an endpoint that is only ever called
 * one way is only tested one way.
 */
export const read: Read = async (year) => {
	const response = await fetch(yearEndpoint(), {
		method: 'POST',
		headers: HEADERS,
		body: new URLSearchParams({
			t: String(year),
			l: '/',
			lng: 'no',
			cata: '',
			customer: CUSTOMER_ID
		}),
		signal: AbortSignal.timeout(30_000)
	});
	if (!response.ok) throw new Error(`${yearEndpoint()} responded ${response.status}`);
	return JSON.parse(await response.text());
};
