<script lang="ts">
	// Self-hosted fonts, not Google Fonts. Google Fonts hotlinking has a GDPR history, and a
	// typeface is not worth an IP disclosure to Google on every page load. We do report page views
	// to one analytics collector (see below) — which is the point: one third party, chosen and
	// written down, is a different thing from picking up another for each asset.
	import '@fontsource-variable/archivo/wdth.css';
	import '@fontsource-variable/archivo/wdth-italic.css';
	import '@fontsource/space-mono/400.css';
	import '@fontsource/space-mono/700.css';
	import '#lib/styles/brand.css';

	import favicon from '#lib/assets/favicon.svg';
	import SiteFooter from '../lib/components/SiteFooter.svelte';
	import SiteMasthead from '../lib/components/SiteMasthead.svelte';
	import { onNavigate } from '$app/navigation';
	import { startAnalytics } from '../lib/analytics.ts';
	import type { LayoutProps } from './$types';

	// Typed, not bare $props() — an untyped destructure makes `children` implicitly any, which
	// CLAUDE.md rule 4 forbids. Kit generates this type for us.
	let { children }: LayoutProps = $props();

	/*
	 * Page analytics, on the live site only.
	 *
	 * In an effect rather than at module scope: this file runs during SSR too, and `window` does
	 * not exist there. The gate is the hostname, so localhost, previews and the end-to-end suite
	 * report nothing — see analytics.ts.
	 */
	$effect(() => {
		void startAnalytics(window.location.hostname);
	});

	/**
	 * Cross-fade between pages, where the browser can.
	 *
	 * Client-side navigation swaps the whole document in one frame, which reads as a flicker rather
	 * than as movement — the one place this site felt least alive. The View Transition API animates
	 * the swap for us.
	 *
	 * Three guards, all of them load-bearing:
	 *
	 * - Feature-detected. Firefox has no `startViewTransition` yet, and calling it there would throw
	 *   on every link.
	 * - Skipped when the reader has asked for reduced motion. The global CSS reset in brand.css
	 *   cannot reach a view transition, because the pseudo-elements it animates are generated by the
	 *   browser and are not `*`.
	 * - Awaited via `complete`, not the promise itself: resolving too early lets SvelteKit finish the
	 *   navigation before the snapshot is taken, and the transition silently does nothing.
	 */
	onNavigate((navigation) => {
		if (!document.startViewTransition) return;
		if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

		return new Promise((resolve) => {
			document.startViewTransition(async () => {
				resolve();
				await navigation.complete;
			});
		});
	});
</script>

<svelte:head>
	<link rel="icon" href={favicon} />
	<meta name="theme-color" content="#1e2c4a" />
</svelte:head>

<a class="skip" href="#innhald">Gå til innhaldet</a>

<SiteMasthead />

<!-- Page chrome lives here so both routes get the same landmarks and the same footer. The landing
     page previously had no <main> at all, which put its h1 and both CTAs inside role=banner —
     precisely the region a screen-reader user skips first. -->
<main id="innhald">
	{@render children()}
</main>

<SiteFooter />

<style>
	.skip {
		position: absolute;
		inset-block-start: 0;
		inset-inline-start: 0;
		z-index: 10;
		transform: translateY(-120%);
		background: var(--peach);
		color: var(--navy-900);
		font-family: var(--font-mono);
		font-size: var(--step-micro);
		font-weight: 700;
		letter-spacing: 0.22em;
		text-transform: uppercase;
		text-decoration: none;
		padding: 1em 1.4em;
	}
	.skip:focus {
		transform: translateY(0);
	}
</style>
